accounts:
  - name: gokul
    coins: ["20000calib", "300000000stake"]
  - name: bob
    coins: ["10000calib", "100000000stake"]
validator:
  name: gokul
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5calib", "100000stake"]
